[features]
seeds = false
[programs.devnet]
nft_marketplace = "EKWmd8gcme68CteJFfXXYtm4vCcPHGGLBtuUnp7DWHJM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ntavigwa/Documents/Keys/nft-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
app = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/**/*.ts"
